# version: '3'
services:
  db:
    image: mysql:latest
    container_name: demo_django_mysql_container
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10
  
  demodjango:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: demo-django_container
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db




  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: demo-nextjs_container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - demodjango
      
volumes:
  data: